---
R1:
    hostname:
    platform: 'ios'
    username:
    password:
    groups:
        - cisco_group

R2:
    hostname:
    platform: 'ios'
    username:
    password:
    groups:
        - cisco_group
