---
R1:
    hostname: 192.168.1.2
    platform: 'ios'
    username: admin
    password: admin
    groups:
        - cisco_group

R2:
    hostname: 192.168.2.2
    platform: 'ios'
    username: admin
    password: admin
    groups:
        - cisco_group
